[ADD] .gitmodules: Add new submodules
Vauxoo/omlimport pull request #1
Opened 2020-06-24 21:47 UTC by hugho-ad

The following sub-modules were added:
- omlimport

2020-06-24 21:54 UTC, luisg123v requested changes
Don't you need `server-tools` for `company_country`?

2020-06-24 21:57 UTC, hugho-ad commented
yes, I've already added it while you commenting

2020-06-25 00:17 UTC, hugho-ad commented
@luisg123v 

please review/merge

2020-06-25 00:25 UTC, luisg123v approved these changes

2020-06-25 00:26 UTC, merged